services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-invest}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-investpw}
      POSTGRES_DB: ${POSTGRES_DB:-investdb}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-invest} -d ${POSTGRES_DB:-investdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      YAHOO_FINANCE_BASE_URL: ${YAHOO_FINANCE_BASE_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  db_data:
